---
title: "Presentations"
---

[video 1](https://www.youtube.com/watch?v=NIiwSfgniyM&ab_channel=jgkix)

Pomona, CA - Cal Poly & Locally Grown Produce, Local Honey, Gifts, U-Pick Berries. Gourmet Grocery Store. Grocery shop at Cal Poly Pomona offering locally grown produce, plus gift baskets & deli sandwiches fresh orange juice.The Farm Store, located at AGRIscapes, features a variety of products and novelty items including produce from the campus farm, orchards, nursery, and greenhouses such as:
Deli sandwiches, cheese, meats and milk products
Cal Poly Pomona grown and locally grown fruits and vegetables
Cal Poly Pomona wines and beers
100% pure and local honey
Grind your own peanut and almond butter
Nursery and ornamental crops such as herbs, potted foliage and flowering plants, annuals and perennials, and landscape container plants
Gift items include our popular fruit gift boxes and custom gift baskets (Located just south of Temple Ave.)
4102 S. University Drive
Pomona, CA